# Site settings
title: Cryptomator Server
description: >
  Cryptomator Server is the new heart of your IT infrastructure. The platform stores your company files and makes them available via network drives. Data is securely protected against ransomware, viruses, data theft, unauthorized access, and data loss.
version: 0.4.0

# Plugins
plugins:
  - jemoji
  - jekyll-redirect-from

# Build settings
sass:
  style: compressed
emoji:
  src: "/assets"

# Collections
collections:
  docs_de:
    output: true
    permalink: /docs/:title/
  docs_en:
    output: true
    permalink: /en/docs/:title/
