# Site settings
title: Defendor
description: >
  Defendor is the new heart of your IT infrastructure. The platform stores your company files and makes them available via network drives. Data is securely protected against ransomware, viruses, data theft, unauthorized access, and data loss.

# Plugins
plugins:
  - jemoji

# Build settings
sass:
  style: compressed
emoji:
  src: "/assets"
