# Site settings
title: Defendor
description: >
  Defendor adds security features, such as anti-malware filters, file encryption, file versioning, and backups, to your corporate cloud- or network-based file storages.

# Plugins
plugins:
  - jemoji

# Build settings
sass:
  style: compressed
emoji:
  src: "/assets"
