version: '3.4'

services:
  wildfly:
    image: skymatic/defendor:0.5.0
    environment:
      - POSTGRES_USER=defendor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=defendor
      - SYSLOG_HOST=syslog
      - SYSLOG_PORT=10514
      - HTTPS_P12_PASSWORD=serverCertP12Passphrase
    ports:
      - 443:8443
    volumes:
      - files:/defendor/files
      - backups:/defendor/backups
#      - /path/to/certs/dev-cert.p12:/wildfly/serverCert.p12:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    depends_on:
      - postgres
    stop_grace_period: 30s

  postgres:
    image: postgres:11.0-alpine
    environment:
      - POSTGRES_USER=defendor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=defendor
    volumes:
      - database:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    stop_grace_period: 15s

  syslog:
    image: skymatic/syslog2pg:4
    environment:
      - POSTGRES_USER=defendor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=defendor
    stop_grace_period: 15s

volumes:
  database:
    name: defendor-db
  files:
    name: defendor-files
  backups:
    name: defendor-backups
